const values = [
  ["1", "Blood Group"],
  ["2", "Bleeding Time", "minutes", "2  –  6 minutes"],
  ["3", "Clotting time", "minutes", "4 – 10 minutes"],
  ["4", "Blood Sugar [R]", "mgs / dl", "80 – 140 mgs / dl"],
  ["5", "Blood sugar [GCT]", "mgs / dl", "80 – 140 mgs / dl"],
  ["6", "Blood Sugar [F]", "mgs / dl", "70 – 110 mgs / dl"],
  ["7", "Blood sugar [PP]", "mgs / dl", "100 – 140 mgs / dl"],
  ["8", "Blood Urea", "mgs / dl", "15  –  40 mgs / dl"],
  ["9", "Serum Creatinine", "mgs / dl", "0.4 – 1.3 mgs / dl"],
  ["10", "HIV"],
  ["11", "HBsAg"],
  ["12", "VDRL"],
  ["13", "SERUM TSH (Thyroid Stimulating Hormone )", "", "0.4 – 4.2"],
  ["14", "Serum LDH ", "U/L", "180 – 360 U/L"],
  ["15", "Bilirubin(Total) ", "mg / dl", "0.1 – 1.2 mg / dl"],
  ["16", "Bilirubin (Direct) ", "mg / dl", "0.0- 0.3 mg / dl"],
  ["17", "Bilirubin (Indirect)"],
  ["18", "Serum Uric acid", "mgs / dl", "3.5 – 7.0 mgs / dl"],
  [
    "19",
    "HB A1C",
    "",
    "NORMAL : 4 – 6 %,GOOD CONTROL : 6 – 7 %,FAIR CONTROL : 7 – 8 %,POOR CONTROL : MORE THAN 8 %",
  ],
  ["20", "Mean Blood Glucose Level"],
  ["21", "Rh Typing"],
  [
    "22",
    "Absolute Eosinophil Count",
    "cells / cu.mm",
    "40 – 440 cells / cu.mm",
  ],
  ["23", "SGOT", "U / L", "5 – 40 U / L"],
  ["24", "SGPT", "U / L", "5 – 41 U / L"],
  ["25", "Polymorphs", "%", "50 – 70 %", "Differential Count"],
  ["26", "Lymphocytes", "%", "30 – 50 %", "Differential Count"],
  ["27", "Eosinaphils", "%", "02 – 06 %", "Differential Count"],
  [
    "28",
    "Total RBC Count",
    "millions / cu.mm",
    "4.5 – 6.0 millions /cu.mm",
    "Differential Count",
  ],
  ["29", "P.C.V", "%", "36 – 47 %", "Differential Count"],
  [
    "30",
    "Platelet Count",
    "Lakhs / cu.mm",
    "1.4 – 4.0 Lakhs/ cu.mm",
    "Differential Count",
  ],
  [
    "31",
    "MCV                                                                 ",
    "fl",
    "80 – 96 fl",
    "Differential Count",
  ],
  [
    "32",
    "MCH                                                                 ",
    "pg",
    "27 – 32 pg",
    "Differential Count",
  ],
  [
    "33",
    "MCHC                                                               ",
    "%",
    "32 – 36 %",
    "Differential Count",
  ],
  ["34", "Basophils", "%", "\u003c 1-2 %", "Differential Count"],
  ["35", "Monocytes", "%", "01 – 08 %", "Differential Count"],
  ["36", "Serum Aylase", "U / L", "28 – 100 U / L", "Differential Count"],
  ["37", "Salmonella typhi O", "", "", "BLOOD WIDAL"],
  ["38", "Salmonella typhi  H", "", "", "BLOOD WIDAL"],
  ["39", "Salmonellpara typhi AH", "", "", "BLOOD WIDAL"],
  ["40", "Salmonella paratyphi BH ", "", "", "BLOOD WIDAL"],
  ["41", "Dengue NS1", "", "", "BLOOD WIDAL"],
  ["42", "Dengue IgG", "", "", "BLOOD WIDAL"],
  ["43", "Dengue IgM", "", "", "BLOOD WIDAL"],
  [
    "44",
    "Haemoglobin",
    "gms / dl",
    "12.5 - 16.0 gms/dl",
    "HAEMOTOLOGY :Complete Blood Count:",
  ],
  [
    "45",
    "Total WBC Count",
    "cells / cu.mm",
    "4000-11000 cells/cu.mm",
    "HAEMOTOLOGY :Complete Blood Count:",
  ],
  ["46", "30 minutes   ", "", "", "E.S.R REPORT:"],
  ["47", "60 minutes", "mm", "10 – 20 mm", "E.S.R REPORT:"],
  ["48", "R.A.Factor", "IU / ml", "upto 20 IU/ml", "E.S.R REPORT:"],
  [
    "49",
    "Serum for C.R.P                          ",
    "mg / L",
    "0 - 6  mg/L",
    "E.S.R REPORT:",
  ],
  [
    "50",
    "CRP (C-Reactive Protein )",
    "mg / L",
    "Upto 6 mg / L",
    "E.S.R REPORT:",
  ],
  ["51", "Urine Bile salt ", "", "", "Urine report "],
  ["52", "Urine Bile pigment ", "", "", "Urine report "],
  ["53", "Albumin", "", "", "Urine report "],
  ["54", "Sugar [R]", "", "", "Urine report "],
  ["55", "Sugar (GCT)", "", "", "Urine report "],
  ["56", "Deposit", "", "", "Urine report "],
  [
    "57",
    "Thyroid Stimulating Hormone (TSH)",
    "ulU / mL",
    "0.4 – 5.5 uIU / mL",
    "IMMUNOLOGY",
  ],
  [
    "58",
    "B- HCG",
    "",
    "Male : Less than 5 , Non Pregnant Female Less than 10.0, 0.2 – 1 week : 5 – 50,\n1 – 2 weeks : 50 – 500,\n2 -3 weeks : 100 -  5,000,\n3 – 4 weeks 500 – 10,000,\n4 – 5 weeks 1,000 – 50,000,\n5 – 6 weeks 10,000 – 1,00,000,\n6 – 8 weeks 15,000 - 2,00,000,\n",
    "IMMUNOLOGY",
  ],
  ["59", "TEST", "", "11.0-15.0", "PROTHROMBIN TIME(PT) :"],
  ["60", "CONTROL", "", "", "PROTHROMBIN TIME(PT) :"],
  ["61", "INR", "", "", "PROTHROMBIN TIME(PT) :"],
  ["62", "RBC", "", "", "PERIPHERAL SMEAR:"],
  ["63", "WBC", "", "", "PERIPHERAL SMEAR:"],
  ["64", "PLATELETS", "", "", "PERIPHERAL SMEAR:"],
  ["65", "IMPRESSION", "", "", "PERIPHERAL SMEAR:"],
  [
    "66",
    "Serum Total Cholesterol ",
    "mgs / dl",
    "140 – 200 mgs / dl",
    "SERUM LIPID PROFILE :",
  ],
  [
    "67",
    "Serum HDL Cholesterol ",
    "mgs / dl",
    "35 – 55 mgs / dl",
    "SERUM LIPID PROFILE :",
  ],
  [
    "68",
    "Serum LDL Cholesterol  ",
    "mgs / dl",
    "70 – 130 mgs / dl",
    "SERUM LIPID PROFILE :",
  ],
  [
    "69",
    "Serum VLDL Cholesterol ",
    "mgs / dl",
    "10- 40 mgs / dl",
    "SERUM LIPID PROFILE :",
  ],
  [
    "70",
    "Serum Triglycerides  ",
    "mgs / dl",
    "45 – 165 mgs / dl",
    "SERUM LIPID PROFILE :",
  ],
  ["71", "T.CHO / HDL RATIO", "", "3.5 – 5.0", "ATHEROGENICITY INDEX RATIO:"],
  ["72", "LDL / HDLRATIO", "", "1.5 – 3.5", "ATHEROGENICITY INDEX RATIO:"],
  ["73", "Sodium", "mMol / L", "136- 145 mMol / L", "ELECTROLYTES"],
  ["74", "Potassium", "mMol / L", "3.5 – 5.1 mMol / L", "ELECTROLYTES"],
  ["75", "Chloride", "mMol / L", "98 – 107 mMol / L", "ELECTROLYTES"],
  ["76", "Bicarbonate", "mMol / L", "22 – 29  mMol / L", "ELECTROLYTES"],
  [
    "77",
    "Bilirubin ( Total )",
    "mgs / dl",
    "0.1 – 1.2 mgs / dl",
    "LIVER FUNCTION TEST",
  ],
  [
    "78",
    "Bilirubin ( Direct )",
    "mgs / dl",
    "0.0 – 0.3 mgs / dl",
    "LIVER FUNCTION TEST",
  ],
  ["79", "Bilirubin ( Indirect )", "", "0.3 - 0.7", "LIVER FUNCTION TEST"],
  ["80", "S.G.O.T", "U / L", "5 – 40 U / L", "LIVER FUNCTION TEST"],
  ["81", "S.G.P.T", "U / L", "5 – 40 U / L", "LIVER FUNCTION TEST"],
  ["82", "Gamma GT", "U / L", "5 – 55 U / L", "LIVER FUNCTION TEST"],
  [
    "83",
    "Alkaline Phosphatase",
    "U / L",
    "53 – 128 U / L",
    "LIVER FUNCTION TEST",
  ],
  [
    "84",
    "Serum Total Protein",
    "gm / dl",
    "6.0 – 8.0 gm / dl",
    "LIVER FUNCTION TEST",
  ],
  [
    "85",
    "Serum Albumin",
    "gm / dl",
    "3.5 – 5.2 gm / dl",
    "LIVER FUNCTION TEST",
  ],
  ["86", "Globulin", "gm / dl", "2.3 – 3.6 gm / dl", "LIVER FUNCTION TEST"],
  ["87", "A/G RATIO", "", "1.1 – 2.2", "LIVER FUNCTION TEST"],
  ["88", "Colour", "", "", "MOTION"],
  ["89", "Ph", "", "", "MOTION"],
  ["90", "Mucus", "", "", "MOTION"],
  ["91", "Consistancy", "", "", "MOTION"],
  ["92", "Occult Blood", "", "", "MOTION"],
  ["93", "Reduction Substance", "", "", "MOTION"],
  ["94", "Ova", "", "", "MICROSCOPIC EXAMINATION"],
  ["95", "Cyst", "", "", "MICROSCOPIC EXAMINATION"],
  ["96", "Test to be done on", "", "", "MANTOUX"],
  ["97", "Please to be read on", "", "", "MANTOUX"],
  [
    "98",
    "Total T3(Triiodothyronine T3)",
    "ng/ dl",
    "70-210 ng / dl",
    "THYROID TEST",
  ],
  [
    "99",
    "Total T4 ( Thyroxine T4)",
    "ug / dl",
    "5.5-11.0 ug / dl",
    "THYROID TEST",
  ],
  [
    "100",
    "Thyroid Stimulating Hormone (TSH)",
    "ulU / mL",
    "0.35 – 5.50 uIU / mL",
    "THYROID TEST",
  ],
];

const parseToArray = () => {
  let data = [];
  values.map((value, index) => {
    let test = {
      id: index + 1,
      name: value[1] ?? "",
      testType: value[4] ? [value[4]] : [],
      unit: value[2] ?? "",
      referenceValue: value[3] ?? "",
    };
    data.push(test);
  });

  console.log(data);
};
